### ISSUE TITLE
Questions for access youth - how they handle requests 

### ISSUE THREAD

**Issue by RachitMalik12** [ubclaunchpad/accessyouth-api#4]
Here a list of questions I came up with after our discussion last week

- Are they catering to specific requests?
- How are requests resolved? Are they resolved by the staff on the bus or by the person itself? How are the youth identified? 
- What personal information are they collecting from the users of the service right now? 

**Questions we have to decide on based on their response**
- How long should a request live? If it is non resolved by the end of the day kill it? (this ties in to how requests are resolved) 
- What should a user enter before requesting?

Feel free to add more so we can resolve any blockers ASAP.

**Comment by fayeyuu** [comment]
Here are the answers l got from Access youth. Let me know if there are any questions/concerns. 

Are they catering to specific requests?
**- They attend to all requests. They don’t have more than 2 phone requests, approximately 1 per night. Generally we will go to where the youth is. If there are more, they would consider “reasons for requests” and “urgency”.**
How are requests resolved? Are they resolved by the staff on the bus or by the person itself? How are the youth identified?
- **It is up to the bus staff to make the call.**
What personal information are they collecting from the users of the service right now?
**- Age, ethnicity (may not continue), male/female, transgender, what were they working on (what issues they are helping the youth), location
- They log the information on a log sheet on the bus**

How long should a request live? If it is non resolved by the end of the day kill it? (this ties in to how requests are resolved)
- **Just one night. Right now no requests get carried over. But It would be good to have the data for the bus worker to see.** We have never had a situation where we won’t be able to get to the kids by a certain time.
What should a user enter before requesting?
- TBD

**Comment by RachitMalik12** [comment]
Thank you @fayeyuu
